// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnlyqdpkxidonkadjpuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZubHlxZHBreGlkb25rYWRqcHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjk4MzcsImV4cCI6MjA3MzcwNTgzN30.bEs2r4iF9FnUQfzKFOTzt-dbHdO_K4M3SwTAiF2bvhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});